
	<div>
		
		<p>
		<h3>Tchater en ligne :</h3> 
		<p>
			Raconter sa vie, se plaindre, ou déblatérer de la merde même si vous avez tort est votre liberté totale sur ce site.

			Les discussions et propos interdits sont :
		</p> 
			<ul>
				<li>insultes répétées</li> 
				<li>discours haineux</li>
				<li>propos racistes</li> 
				<li>propos antisémite</li>
				<li>caractère ou allusion pédophile</li>
				<li>apologie de la torture humaine et animale</li>
			</ul>
		<p>	
			feront l'objet d'un bannissement à vie sur le site tchat.com.

			Bonne discussion à tous et toutes.
		</p>
		
	</div>
	<br>

