
	<div class="containerContent divcontent catStyleContent">
		<h3>Tchater en ligne :</h3> 
		<h4><p>
			Raconter sa vie, se plaindre, ou déblatérer de la merde même si vous avez tort est votre liberté totale sur ce site.<br>
			Cependant les discussions et propos suivants sont interdits:
		</p></h4>
		<br>
		<h4> 
			<ul>
				<li>insultes répétées</li> 
				<li>discours haineux</li>
				<li>propos racistes</li> 
				<li>propos antisémite</li>
				<li>caractère ou allusion pédophile</li>
				<li>apologie de la torture humaine et animale</li>
			</ul>
		</h4>
		<h3><p>
			En cas de non respect de ces règles, vous ferez l'objet d'un bannissement à vie du site tchat.com.
		<p></h3>
		<h4>
			Bonne discussion à tous et toutes.
		</h4>
	</div>
