<div class="cube1">
	<form method="post">
		<!-- login -->
		<div>
			<label for="aliaslogin">Login :</label>
			<input id="aliaslogin" type="text" name="login" placeholder=""/>
		</div>
		<!-- password -->
		<div>
			<label for="aliasmdp">Password :</label>
		    <input id= "aliasmdp" type="password" name="mdp"/>
		</div>
		<!-- Connexion -->
		<div>
			<button type="submit" name="log">Connexion</button>
		</div>
	</form>
</div>