<div class="containerContent divcontent catStyleContent">
	<form method="post">
		<!-- login -->
		<div class="inputRegisterLogin">
			<label for="aliaslogin">Login :</label>
			<input id="aliaslogin" type="text" name="login" placeholder="" class="inputRegisterLogin"/>
		</div>
		<!-- password -->
		<div class="inputRegisterLogin">
			<label for="aliasmdp">Password :</label>
		    <input id= "aliasmdp" type="password" name="password" class="inputRegisterLogin"/>
		</div>
		<!-- Connexion -->
		<div>
			<button type="submit" name="log" class="submitButton catStyleSubmit" class="inputRegisterLogin">Connexion</button>
		</div>
	</form>
</div>