<div class="cube1">
	<form method="post">	
	    	<!-- Nom -->
    	<div>
    		<label for="aliasnom">Nom :</label>
    		<input id="aliasnom" type="text" name="nom" placeholder=""/>
		</div>
		<!-- Prénom -->
		<div>
	    		<label for="aliasprenom">Prénom :</label>
	    		<input id="aliasprenom" type="text" name="prenom" placeholder=""/>
		</div>
		<!-- e-mail -->
		<div>
			<label for="aliasemail">Adresse e-mail :</label>
				<input id="aliasemail" type="text" name="email" placeholder=""/>
		</div>
			<!-- password -->
		<div>
				<label for="aliasmdp">Password :</label>
			    <input id="aliasmdp" type="password" name="mdp"/>
		</div>
		<!-- checkbox -->
			<div>
			<label for="aliasvalid">je ne suis pas un robot</label>
			<input id="aliasvalid" type="checkbox" name="valid" value="1">    	
		</div>
		<!-- valid -->
		<div>
			<button type="submit">Envoyer</button>
		</div>
	</form>
</div>