<div class="containerContent divcontent catStyleContent">
	<form method="post" class="">	
	    	<!-- Nom -->
		<div class="inputRegisterLogin">
    		<label for="aliaslogin">Login :</label>
    		<input id="aliaslogin" type="text" name="login" class="inputRegisterLogin"required/>
		</div>
		<!-- Prénom -->
		<div class="inputRegisterLogin">
    		<label for="aliaspassword" class="labelRegisterLogin">Password :</label>
    		<input id="aliaspassword" type="password" name="password" class="inputRegisterLogin" required/>
		</div>
			<!-- password -->
		<div class="inputRegisterLogin">
			<label for="aliaspassword2" class="labelRegisterLogin">Password :</label>
		    <input id="aliaspassword2" type="password" name="password2" class="inputRegisterLogin" required/>
		</div>
		<!-- checkbox -->
		<div class="inputRegisterLogin">
			<label for="aliasvalid" class="labelRegisterLogin">je ne suis pas un robot</label>
			<input id="aliasvalid" type="checkbox" name="robot" class="translatY">    	
		</div>
		<!-- valid -->
		<div>
			<button type="submit" name="register" class="submitButton catStyleSubmit">Envoyer</button>
		</div>
	</form>
</div>