<div class="cube1">
	<form method="post">	
	    	<!-- Nom -->
    	<div>
    		<label for="aliaslogin">Login :</label>
    		<input id="aliaslogin" type="text" name="login" required/>
		</div>
		<!-- Prénom -->
		<div>
	    		<label for="aliaspassword">Password :</label>
	    		<input id="aliaspassword" type="password" name="password" required/>
		</div>
			<!-- password -->
		<div>
				<label for="aliaspassword2">Password :</label>
			    <input id="aliaspassword2" type="password" name="password2"  required/>
		</div>
		<!-- checkbox -->
			<div>
			<label for="aliasvalid">je ne suis pas un robot</label>
			<input id="aliasvalid" type="checkbox" name="robot">    	
		</div>
		<!-- valid -->
		<div>
			<button type="submit">Envoyer</button>
		</div>
	</form>
</div>