<div class="containerContent divcontent catStyleContent">
	<div id="input" >
            <!-- les messages du tchat -->
			<?php require('apps/list_message.php'); ?>
    </div>
	<div>
		<form id="form" method="POST" >
		    Pseudo : <?=htmlentities($user->getLogin())?><br />
		    <div class="labelInputMessage"><h4>Message :</h4></div>
		    <textarea autofocus name="message" id="message" class="inputMessage"></textarea><br />
		   
		    <button type="submit" name="submit" class="submitButton catStyleSubmit">Valider</button>
		</form>
	</div>
</div>